import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f1f5f9',
  },
  headerWrap: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  headerGradient: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#0f172a',
  },
  brand: {
    color: '#93c5fd',
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 1,
  },
  headerTitle: {
    marginTop: 4,
    fontSize: 24,
    fontWeight: '800',
    color: '#f8fafc',
  },
  headerSubtitle: {
    marginTop: 4,
    color: '#cbd5e1',
    fontSize: 13,
  },
  headerMetaRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  headerStatusBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  headerStatusBadgeUp: {
    backgroundColor: '#dcfce7',
    color: '#166534',
  },
  headerStatusBadgeDown: {
    backgroundColor: '#fee2e2',
    color: '#b91c1c',
  },
  headerMetaText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
  },
  apiText: {
    marginTop: 10,
    color: '#94a3b8',
    fontSize: 11,
  },
  tabRow: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  tabButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  tabText: {
    color: '#334155',
    fontSize: 14,
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#ffffff',
  },
  loadingWrap: {
    padding: 16,
    alignItems: 'center',
  },
  errorBox: {
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    padding: 12,
    gap: 4,
  },
  errorTitle: {
    color: '#b91c1c',
    fontSize: 13,
    fontWeight: '800',
  },
  errorText: {
    color: '#991b1b',
    fontSize: 12,
  },
  retryButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    borderRadius: 999,
    backgroundColor: '#7f1d1d',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  scroll: {
    flex: 1,
  },
  content: {
    padding: 16,
    gap: 10,
    paddingBottom: 30,
  },
  primaryCard: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 14,
    gap: 6,
  },
  card: {
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 14,
    gap: 10,
  },
  cardEyebrow: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  cardTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  searchInput: {
    marginTop: 2,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#0f172a',
    fontSize: 14,
  },
  quickStatsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  quickStatCard: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 10,
  },
  quickStatValue: {
    marginTop: 4,
    color: '#0f172a',
    fontSize: 22,
    fontWeight: '800',
  },
  stockResultRow: {
    gap: 8,
  },
  stockResultCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 12,
    gap: 6,
  },
  stockResultCardActive: {
    borderColor: '#0f766e',
    backgroundColor: '#ecfdf5',
  },
  stockResultTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  stockResultName: {
    flex: 1,
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
  },
  stockMarketBadge: {
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  stockMarketBadgeKr: {
    backgroundColor: '#dbeafe',
    color: '#1d4ed8',
  },
  stockMarketBadgeUs: {
    backgroundColor: '#ede9fe',
    color: '#6d28d9',
  },
  stockResultMeta: {
    color: '#64748b',
    fontSize: 12,
    fontWeight: '600',
  },
  stockResultBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  stockResultPrice: {
    color: '#0f172a',
    fontSize: 16,
    fontWeight: '800',
  },
  stockResultDelta: {
    fontSize: 13,
    fontWeight: '800',
  },
  favoriteHint: {
    color: '#0f766e',
    fontSize: 11,
    fontWeight: '700',
  },
  stockDetailHero: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  stockDetailName: {
    color: '#0f172a',
    fontSize: 20,
    fontWeight: '800',
  },
  stockDetailPrice: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  cardSection: {
    gap: 10,
    marginTop: 6,
  },
  noteInput: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  inlineButtonRow: {
    flexDirection: 'row',
    gap: 8,
  },
  primaryActionButton: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryActionButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  secondaryActionButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  secondaryActionButtonText: {
    color: '#334155',
    fontSize: 13,
    fontWeight: '800',
  },
  stockInsightCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 12,
    gap: 6,
  },
  favoriteRow: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  favoriteDeleteButton: {
    borderRadius: 999,
    backgroundColor: '#fee2e2',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  favoriteDeleteText: {
    color: '#b91c1c',
    fontSize: 12,
    fontWeight: '800',
  },
  primaryValue: {
    color: '#0f172a',
    fontSize: 23,
    fontWeight: '800',
  },
  cardNote: {
    color: '#475569',
    fontSize: 13,
    lineHeight: 18,
  },
  metaText: {
    color: '#64748b',
    fontSize: 12,
  },
  kpiRow: {
    flexDirection: 'row',
    gap: 8,
  },
  heroMetricsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  heroMetricCard: {
    flex: 1,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dbeafe',
    padding: 12,
    gap: 6,
  },
  heroMetricCardDark: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  heroMetricLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  heroMetricLabelOnDark: {
    color: '#93c5fd',
  },
  heroMetricValue: {
    color: '#0f172a',
    fontSize: 18,
    fontWeight: '800',
  },
  heroMetricValueOnDark: {
    color: '#f8fafc',
  },
  heroMetricFootnote: {
    color: '#64748b',
    fontSize: 11,
    lineHeight: 16,
  },
  heroMetricFootnoteOnDark: {
    color: '#cbd5e1',
  },
  kpiCard: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    alignItems: 'center',
  },
  kpiLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  kpiValue: {
    marginTop: 4,
    color: '#0f172a',
    fontSize: 17,
    fontWeight: '800',
  },
  sessionCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#f8fafc',
    gap: 4,
  },
  sessionTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sessionName: {
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
  },
  sessionBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    fontSize: 11,
    fontWeight: '700',
    overflow: 'hidden',
  },
  sessionMeta: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  sessionNote: {
    color: '#64748b',
    fontSize: 12,
  },
  metricRow: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#f8fafc',
    gap: 3,
  },
  metricLeft: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metricName: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  metricState: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '600',
  },
  metricScore: {
    color: '#0f766e',
    fontSize: 18,
    fontWeight: '800',
  },
  metricNote: {
    color: '#64748b',
    fontSize: 12,
  },
  metricSource: {
    color: '#0369a1',
    fontSize: 11,
    fontWeight: '700',
  },
  alternativeMetricRow: {
    gap: 8,
  },
  alertMetricRow: {
    gap: 8,
  },
  alternativeMetricTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  alternativeScoreBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '800',
    overflow: 'hidden',
  },
  alternativeHighlightsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  alternativeHighlightChip: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: 'rgba(15, 23, 42, 0.06)',
    color: '#334155',
    fontSize: 11,
    fontWeight: '700',
    overflow: 'hidden',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  summaryRow: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 10,
    backgroundColor: '#f8fafc',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  summaryValueBox: {
    alignItems: 'flex-end',
    gap: 2,
  },
  summaryMeta: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '700',
  },
  summaryDelta: {
    fontSize: 12,
    fontWeight: '700',
  },
  portfolioSummaryRow: {
    flexDirection: 'row',
    gap: 8,
  },
  portfolioSummaryCard: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 10,
  },
  briefingList: {
    gap: 8,
    marginTop: 10,
  },
  briefingBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  briefingBullet: {
    color: '#0f766e',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 1,
  },
  briefingItem: {
    flex: 1,
    color: '#334155',
    fontSize: 13,
    lineHeight: 20,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
    marginBottom: 4,
    flexWrap: 'wrap',
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  filterChipActive: {
    borderColor: '#0f172a',
    backgroundColor: '#0f172a',
  },
  filterText: {
    color: '#334155',
    fontWeight: '700',
    fontSize: 12,
  },
  filterTextActive: {
    color: '#ffffff',
  },
  indexChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  indexChip: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#ffffff',
  },
  indexChipActive: {
    borderColor: '#0369a1',
    backgroundColor: '#e0f2fe',
  },
  indexChipText: {
    color: '#334155',
    fontWeight: '700',
    fontSize: 12,
  },
  indexChipTextActive: {
    color: '#0c4a6e',
  },
  chartWrap: {
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  chartAxisRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  chartAxisLabel: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '600',
  },
  emptyChart: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
  },
  legendRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  legendText: {
    fontSize: 12,
    fontWeight: '700',
  },
  chartStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  chartStat: {
    minWidth: '47%',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    padding: 8,
  },
  chartStatValue: {
    marginTop: 2,
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '700',
  },
  logTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  logName: {
    flex: 1,
    color: '#0f172a',
    fontSize: 14,
    fontWeight: '700',
  },
  logStage: {
    color: '#475569',
    fontSize: 11,
    fontWeight: '700',
    backgroundColor: '#e2e8f0',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    overflow: 'hidden',
  },
  logMeta: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '600',
  },
  logBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  badge: {
    color: '#334155',
    fontSize: 11,
    fontWeight: '700',
    backgroundColor: '#e2e8f0',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    overflow: 'hidden',
  },
})
